<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3GtMxxb\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3GtMxxb/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container3GtMxxb.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container3GtMxxb\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container3GtMxxb\srcDevDebugProjectContainer(array(
    'container.build_hash' => '3GtMxxb',
    'container.build_id' => 'f473f0f8',
    'container.build_time' => 1540383902,
), __DIR__.\DIRECTORY_SEPARATOR.'Container3GtMxxb');
