<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1YuUuOX\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1YuUuOX/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container1YuUuOX.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container1YuUuOX\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container1YuUuOX\srcDevDebugProjectContainer(array(
    'container.build_hash' => '1YuUuOX',
    'container.build_id' => '89b8b58c',
    'container.build_time' => 1541001435,
), __DIR__.\DIRECTORY_SEPARATOR.'Container1YuUuOX');
