<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMwm6shE\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMwm6shE/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMwm6shE.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMwm6shE\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerMwm6shE\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Mwm6shE',
    'container.build_id' => 'c9250f24',
    'container.build_time' => 1541503125,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMwm6shE');
